// strong id wrappers so a node id can't be passed where a conversation id is
// wanted. ids are opaque strings (sortable, time-prefixed) generated by new_id.
#pragma once

#include <compare>
#include <functional>
#include <string>
#include <utility>

namespace plume {

template <typename Tag>
struct strong_id {
	std::string value;

	strong_id() = default;
	explicit strong_id(std::string v) : value(std::move(v)) {}

	auto operator<=>(const strong_id&) const = default;
	[[nodiscard]] bool empty() const noexcept { return value.empty(); }
	[[nodiscard]] const std::string& str() const noexcept { return value; }
};

struct convo_tag {};
struct node_tag {};
struct attachment_tag {};

using convo_id = strong_id<convo_tag>;
using node_id = strong_id<node_tag>;
using attachment_id = strong_id<attachment_tag>;

// lexicographically sortable, roughly time-ordered, unique. prefix identifies
// the kind so a stray id is legible in a log or the db.
[[nodiscard]] std::string new_id(std::string_view prefix);

}  // namespace plume

template <typename Tag>
struct std::hash<plume::strong_id<Tag>> {
	std::size_t operator()(const plume::strong_id<Tag>& id) const noexcept {
		return std::hash<std::string>{}(id.value);
	}
};
